
version: "3.9"

networks:
  network:
volumes:
  DB:
    driver: local
    driver_opts: 
      type: none
      device: /home/kiwi/databases/DB
      o: bind
  WordPress:
    driver: local
    driver_opts:
      type: none
      device: /home/kiwi/databases/WordPress
      o: bind
services:
  mariadb:
    image: "inception:mariadb"
    env_file: 
      - .env
    build:
      context: ./requirements/mariadb
      args:
        - NAME=$NAME
        - USER=$USER
        - ROOT=$ROOT
        - PASSUSER=$PASSUSER
        - PASSROOT=$PASSROOT
    volumes:
      - DB:/var/lib/mysql
    networks: 
      - network
    restart: always
  wordpress:
    depends_on: 
      - mariadb
    image: "inception:wordpress"
    env_file:
      - .env
    build: ./requirements/wordpress
    volumes:
      - WordPress:/var/www/html
    networks:
      - network
    restart: always
  nginx:
    depends_on:
      - wordpress
    image: "inception:nginx"
    ports:
      - "443:443"
    build: ./requirements/nginx
    volumes:
      - WordPress:/var/www/html
    networks:
      - network
    restart: always

